/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    'root': RouteRecordInfo<'root', '/', Record<never, never>, Record<never, never>>,
    'auth-sign-in': RouteRecordInfo<'auth-sign-in', '/auth/sign-in', Record<never, never>, Record<never, never>>,
    'dashboard': RouteRecordInfo<'dashboard', '/dashboard', Record<never, never>, Record<never, never>>,
    'dashboard-info': RouteRecordInfo<'dashboard-info', '/dashboard/info', Record<never, never>, Record<never, never>>,
    'dashboard-produk': RouteRecordInfo<'dashboard-produk', '/dashboard/produk', Record<never, never>, Record<never, never>>,
    'dashboard-produk-slug': RouteRecordInfo<'dashboard-produk-slug', '/dashboard/produk/:slug', { slug: ParamValue<true> }, { slug: ParamValue<false> }>,
    'dashboard-produk-add': RouteRecordInfo<'dashboard-produk-add', '/dashboard/produk/add', Record<never, never>, Record<never, never>>,
    'produk': RouteRecordInfo<'produk', '/produk', Record<never, never>, Record<never, never>>,
    'produk-slug': RouteRecordInfo<'produk-slug', '/produk/:slug', { slug: ParamValue<true> }, { slug: ParamValue<false> }>,
    'tentang': RouteRecordInfo<'tentang', '/tentang', Record<never, never>, Record<never, never>>,
  }
}
